name: Build and Publish Docker image

on:
  push:
    branches: [main]

jobs:
  docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: false
          envkey_NEXT_PUBLIC_BACKEND_URL: "http://localhost:5002"
          file_name: .env
      # - name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v3
      #   with:
      #     username: ${{ vars.DOCKER_USER }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ vars.DOCKER_USER }}/dia-ui
      #     readme-filepath: ./README.md
      - name: Build and push
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USER }}/dia-ui:latest
          platforms: linux/amd64,linux/arm64/v8
